theme: jekyll-theme-architect
title: Gökhan KOCA Progress Journal
description: BDA 503 Fall 2019 - Mef University
navbar:
  left:
    - text: "Home"
      href: index.html
    - text: "About"
      href: about.html
